image: silkeh/clang

before_script:
  - apt-get update -yq
  - apt-get install -yq clang libcurl4-openssl-dev
  - ldconfig

build:
  stage: build
  script:
    - cd tests
    - make all
    - cd ../benchmark
    - make benchmark
  artifacts:
    paths:
      - "tests/*_test"
      - "benchmark/benchmark"

test:
  stage: test
  script:
    - cd tests
    - export 'ASAN_OPTIONS=detect_leaks=0'
    - make test

benchmark:
  stage: test
  script:
    - cd benchmark
    - yes | .benchmark
  artifacts:
    paths:
      - "data/benchmark/*"
