image: silkeh/clang

before_script:
  - apt-get update -yq
  - apt-get install -yq clang libcurl4-openssl-dev
  - ldconfig

build:
  stage: build
  script:
    - cd tests
    - make all
  artifacts:
    paths:
      - "tests/*_test"

test:
  stage: test
  script:
    - cd tests
    - export 'ASAN_OPTIONS=detect_leaks=0'
    - make test
