image: silkeh/clang

build:
  stage: build
  before_script:
    - apt-get update && apt-get upgrade && apt -y install clang
  script:
    - cd tests
    - make all
  artifacts:
    paths:
      - "tests/*_test"

test:
  stage: test
  script:
    - cd tests
    - export 'ASAN_OPTIONS=detect_leaks=0'
    - ./coordinates_test
    - ./vehicles_test
    - ./stations_test
