image: silkeh/clang

build:
  stage: build
  before_script:
    - apt-get update -yq
    - apt-get install -yq clang libcurl4-openssl-dev libjson-c-dev
  script:
    - cd tests
    - make all
  artifacts:
    paths:
      - "tests/*_test"

test:
  stage: test
  script:
    - cd tests
    - export 'ASAN_OPTIONS=detect_leaks=0'
    - make test
