image: silkeh/clang

build:
  stage: build
  script:
    - cd tests
    # - make all
  artifacts:
    paths:
      - "tests/*_test"

test:
  stage: test
  script:
    - cd tests
    - export 'ASAN_OPTIONS=detect_leaks=0'
